server:
  port: 8081

spring:
  application:
    name: Student-micro

  config:
    import: optional:configserver:http://localhost:8083

  datasource:
    url: jdbc:mysql://localhost:3306/studentdata
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


#  security:
#    user:
#      name: admin
#      password: admin123

